### ISSUE TITLE
NY Touring Route Book Update

### ISSUE THREAD

**Issue by vdeane** [TravelMapping/HighwayData#1061]
There was just a new release of the NY Touring Route Book.  Many of the changes have already been done in TravelMapping, but there are a few that haven't:
-NY 191 decommissioned
-NY 220 truncated to NY 12
-NY 261 truncated to Lake Ontario State Parkway
-NY 430 realigned in Jamestown to take Washington Street to NY 60/NY 394
-NY 8 truncated to NY 10

There's discussion on AA Roads, currently spread in multiple locations between the top and bottom of the page: http://www.aaroads.com/forum/index.php?topic=1487.2700
https://www.dot.ny.gov/divisions/operating/oom/transportation-systems/repository/2017%20tour-bk.pdf

**Comment by yakra** [comment]
#1099 addresses NY191 & NY430. I'm holding off on the others for now, until other data sources agree, there are reports of changed signage in the field, or I'm otherwise satisfied it's time to make the changes.

FWIW, for New York changes, the forum is probably a more sure-fire way to get my attention. I don't check GitHub notifications terribly often, and when I do, new issues can get lost in the noise among all the other HighwayData pull requests.

**Comment by vdeane** [comment]
I just looked at some street view dated 2012.  Looks like NY 261 has been signed to end at the Parkway for a while now.

**Comment by yakra** [comment]
NY261 truncated in #1106.

__This leaves:__
-NY 220 truncated to NY 12
-NY 8 truncated to NY 10

**Comment by yakra** [comment]
Finally caught up with the rest of the New York thread on AARoads. Based on the discussion there, I'm going to close this issue. If any new info comes to light that makes NY8 or 220 worth reconsidering, we can reopen, open a new issue/forum thread, etc.
