### ISSUE TITLE
PA 378 and PA 412

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#111]
Received by email from user wadsteckel: PA378 and PA412 need one more waypoint
each to coincide with the 2nd Avenue ramp connecting the two.

**Comment by rickmastfan67** [comment]
I'm looking into this issue right now.

**Comment by rickmastfan67** [comment]
Alright, I've added points for the 2nd Street (not Ave) Ramp to both routes in #396.

I've also added in the missing 'Main Street' ramp from PA-378, as well as added an intersection for '3rd Street' since people coming from PA-412 might miss it's left turn @ the 2nd Street Ramp since it's very poorly posted per StreetView.
