### ISSUE TITLE
UT: Is there a Utah 289 in Cedar City?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#118]
I was in Cedar City today at Southern Utah University, and realized I did not see any signs for UT 289.  It's currently in our in-development usaut system.  I will be back in that area tomorrow and will take another look to see if I can find any evidence of signage for the route.

**Comment by jteresco** [comment]
I looked more today, no sign of any sign.  I think we should remove it from the usaut set before activation.  Opinions?

**Comment by yakra** [comment]
Agreed.

**Comment by ovoss** [comment]
I agree. Especially since this is one of those short routes whose only 
function seems to be to connect a state college/university or other 
institution to the state highway system. There are other similar routes 
around Utah (I saw a few in the 28x and 29x number range) that Nick should 
perhaps check out in GMSV for signage if he hasn't already, in case they 
turn out to be the same story as with UT 289..

I'd add that when I'm ready to put Alaska State Highways out for review, 
I'll argue for a modest lightening of CHM's usual exclusion of unsigned 
routes, so we can include two unsigned segments (both > 30 miles long) of 
otherwise signed Alaska routes. But I don't think any change in policy 
should apply here.

----- Original Message -----

**Comment by NickCPDX** [comment]
Hey folks… found you here. 

I can't find a Utah 289 sign on GMSV anywhere. I'm sure there's a reason I decided to include it but hey, if it's unsigned, it's unsigned.

**Comment by the-spui-ninja** [comment]
Posting stuff that I put on the AARoads data updates thread...
UDOT says it still exists. http://www.udot.utah.gov/main/uconowner.gf?n=7057009304316097
Then again, that's from 2008...
Here is a list of all the highways in Utah, for future reference: http://www.udot.utah.gov/main/f?p=100:pg:0:::1:T,V:814,

Also, TM is missing a lot of the higher-numbered routes in that list. Granted, there are several route numbers reserved for "all the roads and parking lots in x", but some of those are actual roads that go somewhere (UT 310, 312, and 314 come to mind)

Aaaand yet another edit, here's a good resource for checking the Utah State Highways set: https://maps.udot.utah.gov/highway/f?p=184:4 (be sure to click show state routes)
This one does include the parking lot highways, so that's kinda neat.

There's a ton of routes that either need to be added or decided firmly not to add them (if that makes any sense). 

If the URLs don't work you can just copy or paste them.

**Comment by the-spui-ninja** [comment]
Again, if it's unsigned, it's unsigned, but this needs to be done with a lot more than just 289.

**Comment by NickCPDX** [comment]
Thanks. With routes like 310, etc, those are not only unsigned but short. I recall discussion back when the system was in development for CHM that those routes do not need to be in the system.

We spent more than a year working on this system back in CHM and it was vetted several times. I think it's ready to go.

**Comment by ovoss** [comment]
Have the Datacheck errors been addressed? Datacheck isn't working at the 
moment, so I can't tell.

Also, a once-over for things that've changed (both UT routes, and 
intersecting I-/US routes) since the system was last worked on. We picked up 
a few of those in NM, where like in UT the in-dev state route system has 
been sitting around for awhile after peer review. Good to take care of that 
before activation, rather than activate then have to do a flurry of updates 
afterward.

On unsigned routes, I think routes known to be unsigned (including any that 
have recently become unsigned, like perhaps UT 289) should be taken out, 
unless there is a good reason to leave them in. Under CHM, I'd be surprised 
if Tim would've let any of them slip through. Under new management, we might 
loosen that a little, but I think only a little.

----- Original Message -----

**Comment by the-spui-ninja** [comment]
What about routes like UT 315 that extend beyond the point that they are in the in-dev system? 

Also, UT 190 and UT 284 need to be looked at; their alignments don't match up to the state route guide I linked earlier.

**Comment by jteresco** [comment]
Datacheck is back.  Let's address those (I assume most are FPs) and the known things that need fixing then get this thing activated.  I see no need for another full-fledged round of peer review, but if there are a few things to address, let's address them before rather than after.  Surely some things will slip through but that's OK.

**Comment by jteresco** [comment]
Of course the datacheck responsibilities no longer really need to fall on just one person.  Anyone with a few minutes of time here and there can run through some of the datacheck, especially when it's just a matter of reporting FPs.

**Comment by si404** [comment]
Datacheck FPs: note that this is NOT all of them - there's a few (8) visible distances that can be fixed.

ut.ut009;ZionCanDr;+X905882;+X189571;SHARP_ANGLE;169.27
ut.ut009;+X905882;+X189571;+X107992;SHARP_ANGLE;169.89
ut.ut009;+X189571;+X107992;+X671604;SHARP_ANGLE;147.73
ut.ut009;+X107992;+X671604;ZionTunE;SHARP_ANGLE;159.10
ut.ut021;WahWahRd;PineValRd_S;;VISIBLE_DISTANCE;10.38
ut.ut036;PonyExpRd;UT199;;VISIBLE_DISTANCE;12.45
ut.ut044;SheCrkRd;+X461360;+X606617;SHARP_ANGLE;139.45
ut.ut092;+X872493;+X749820;+X716056;SHARP_ANGLE;141.23
ut.ut095;UT276_N;HiteVP;;VISIBLE_DISTANCE;14.39
ut.ut095;RadKinRd;MossBackRd;;VISIBLE_DISTANCE;10.66
ut.ut128;US191;LasMtnRd;;VISIBLE_DISTANCE;15.05
ut.ut137;+X284496;100W;US89_N;SHARP_ANGLE;138.85
ut.ut153;OakBasRd;+X852604;+X818363;SHARP_ANGLE;146.46
ut.ut190;+X590758;BriRes;GuaPassRd;SHARP_ANGLE;160.33
ut.ut190;+X504333;+X623693;+X791264;SHARP_ANGLE;145.57
ut.ut190;+X623693;+X791264;End;SHARP_ANGLE;135.27
ut.ut224;End;+X673185;EmpCan;SHARP_ANGLE;138.15
ut.ut224;+X673185;EmpCan;+X929661;SHARP_ANGLE;166.44
ut.ut257;GeoPlaRd;17300S;;VISIBLE_DISTANCE;10.58
ut.ut257;Bloom;CleLakeRd;;VISIBLE_DISTANCE;13.37
ut.ut261;ValGodsRd;+X724592;+X493870;SHARP_ANGLE;147.48
ut.ut261;+X493870;+X763016;+X366669;SHARP_ANGLE;163.96
ut.ut261;+X763016;+X366669;+X183625;SHARP_ANGLE;155.99
ut.ut261;+X183625;+X409783;+X948785;SHARP_ANGLE;165.40
ut.ut276;CalBlaAir;HallCroRd;;VISIBLE_DISTANCE;10.27
ut.ut282for;UT282;;;LABEL_SELFREF;
ut.ut282mou;UT282;;;LABEL_SELFREF;
ut.ut287;UT140;PonyExpRd_N;UtahStaPri;SHARP_ANGLE;141.34
ut.ut289;UT289_S;;;LABEL_SELFREF;
ut.ut289;UT289_S;UT289;;DUPLICATE_COORDS;(37.677333,-113.066847)
ut.ut289;UT289;;;LABEL_SELFREF;
ut.ut313;+X949487;+X395493;+X160681;SHARP_ANGLE;149.25

**Comment by the-spui-ninja** [comment]
I think this one: ut.ut190;+X590758;BriRes;GuaPassRd;SHARP_ANGLE;160.33
means UT 190 should be broken up into two segments.

But that's just me.

**Comment by si404** [comment]
@the-spui-ninja - why? Can you not drive between the segments? It's a junction on a hairpin bend.

**Comment by the-spui-ninja** [comment]
Well, what I see is that the segment between BriRes and GuaPassRd is actually its own segment, and the route bypasses it before coming to it (if that makes any sense). Here it is in the HB so you can see what I'm talking about. http://www.teresco.org/~terescoj/travelmapping/devel/hb.php?r=ut.ut190

**Comment by si404** [comment]
I see what you mean, having looked at it in MapQuest Open, and not just pinning it on google maps being crappy.

**Comment by the-spui-ninja** [comment]
When I was there, signage seemed to indicate that UT 190 went around the Brighton loop road, but then I wasn't really paying attention because the scenery was awesome.

**Comment by the-spui-ninja** [comment]
Should I start an issue for all the non-FP errors that we find in the Utah routes? (like what was with UT 190)

**Comment by jteresco** [comment]
@the-spui-ninja I think that's a good idea.

**Comment by jteresco** [comment]
General discussion of pre-activation fixup of usaut moved to #138.  As far as this issue, I'm going to go ahead and remove UT 289.  Once it's committed, I'll close the issue.

**Comment by NickCPDX** [comment]
Can we cross-reference the above errorcheck list with the one on the old CHM forum (which I would copy and paste but don't have access to right now)?

**Comment by si404** [comment]
The list of false errors on the CHM forum was already integrated. The above ones (save the UT190 issue) have been added to them. There should be about 6 possible errors left for this system - all visible distance ones where I found a side turn that could be added.

**Comment by NickCPDX** [comment]
Responses to errorcheck - 

Sharp angles on all - There were reasons for including those – mostly for cutting too much length from a route if excluded. 

On the longer stretches without waypoints, I mean, it's Utah. Many of the side roads that might show up on mapping software would be hard to spot if you were driving by. For example, on UT 95, here is something shown on Google Maps as a road on a longer stretch between waypoints.

https://www.google.com/maps/@37.5933434,-110.0431948,3a,75y,77.25h,81.72t/data=!3m6!1e1!3m4!1s58vZJQwPToAlqxm785yDvw!2e0!7i3328!8i1664

Somewhere in some BLM archive they probably have a name for that road, but I haven't been able to find it. I just think there's not much point to adding a waypoint for waypoints' sake. But if someone disagrees, I think we should wager a beer for all waypoints added … I owe a beer for every time one is used, and you owe me a beer a year for every waypoint we add that goes unused.

UT 128 - Should we add one at a campground in the canyon? 

UT 282 - This was discussed on the CHM forum. The goofy state route around the U campus.

UT 289 - Pull the route.

**Comment by jteresco** [comment]
Copying the @NickCPDX comment above to the current Utah issue.

**Comment by ovoss** [comment]
On longer stretches without waypoints -- none of then are longer than 20 
miles, and even much longer ones (like a few over 50 miles in the Arctic) we 
don't get too desperate to add waypoints rather than just write them off as 
false positives.

If you haven't already, look at the readily available online maps like 
Mapnik/OSM, MQ Open, Google and Bing, perhaps also at a route log if you 
have one (like I used in Alaska and other Arctic jurisdictions). If you 
still can't come up with a name for an intersecting road, ignore it and 
write off the affected segment as an FP.

I'm partial to including campgrounds as waypoints, as places where a 
non-trivial number of travelers might turn around and go back the way they 
came. But unless you need the one on UT 128 to clear a Datacheck error (and 
it looks like you don't), I wouldn't bother.

----- Original Message -----

**Comment by jteresco** [comment]
So we don't lose anything in this closed issue, let's continue this discussion in #138.
