### ISSUE TITLE
TX: Partial-freeway USANSF routes, and USATX, USATXL & USATXS

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#134]
Right now, there are five TX routes in USANSF that were truncated to only include a freeway portion:
TX114, TX121, TXLp12, TXSpr348 and TXLp1604.
These would have to be extended when the Texas State Highways, Loops and Spurs go live.
(See their proposed final configurations at: https://github.com/yakra/HighwayData/tree/TX-temp/hwy_data/TX/TEMP )

I'm looking for input on how to handle the peer review / pre-activation phase.
Though the Roots would differ (E.G. tx.tx114 vs tx.tx114fwy), the Region+Route combos (TX TX114 vs TX TX114) would cause collisions & wacky hijinks in the DB if we just plopped `em into USATX, USATXL & USATXS straight away while the routes are still in USANSF.

I see a couple ways to handle this:

1.) While in the peer review / pre-activation phase, temporarily rename these routes in their respective system CSVs to avoid collisions. We could have, say, TX114X, TX121X, TXLp12X, TXSpr348X and TXLp1604X. Once their respective systems go live, we remove the old truncated routes from USANSF, and rename the new routes in the CSVs. "TX TX114" would point to tx.tx114 instead of tx.tx114fwy, the transition happens seamlessly, and life goes on.

2.) Just extend the activated routes already in USANSF, to include their full length. Leave them out of the USATX* CSVs entirely while those are under peer review. When these systems go live, move the already-extended routes over from USANSF. There's already precedent for some full routes with substantial non-freeway portions included in USANSF, most notably TX183 & TX191.

What do y'all think?

-----
Note to self: deprecated labels as needed? (I see a few, but be sure.)

**Comment by ovoss** [comment]
I prefer option (2), if only because it makes all of TXLp1604 mappable more 
quickly (having only part of that big San Antonio loop mapped just looks 
weird). Just ask for comments on those routes before they are changed in 
USANSF, so they need not be reviewed again when the new TX systems go out 
for review.

Oscar

----- Original Message ----- 
From: Eric Bryant
To: TravelMapping/HighwayData
Sent: Tuesday, October 13, 2015 12:01 PM
Subject: [HighwayData] TX: Partial-freeway USANSF routes, and USATX, USATXL 
& USATXS (#134)


Right now, there are five TX routes in USANSF that were truncated to only 
include a freeway portion:
TX114, TX121, TXLp12, TXSpr348 and TXLp1604.
These would have to be extended when the Texas State Highways, Loops and 
Spurs go live.
(See their proposed final configurations at: 
https://github.com/yakra/HighwayData/tree/TX-temp/hwy_data/TX/TEMP )
I'm looking for input on how to handle the peer review / pre-activation 
phase.
Though the Roots would differ (E.G. TX114 vs TX114Fwy), the Region+Route 
combos (TX TX114 vs TX TX114) would cause collisions & wacky hijinks in the 
DB if we just plopped `em into USATX, USATXL & USATXS straight away while 
the routes are still in USANSF.
I see a couple ways to handle this:
1.) While in the peer review / pre-activation phase, temporarily rename 
these routes in their respective system CSVs to avoid collisions. We could 
have, say, TX114X, TX121X, TXLp12X, TXSpr348X and TXLp1604X. Once their 
respective systems go live, we remove the old truncated routes from USANSF, 
and rename the new routes in the CSVs. "TX TX114" would point to tx.tx114 
instead of tx.tx114fwy, the transition happens seamlessly, and life goes on.
2.) Just extend the activated routes already in USANSF, to include their 
full length. Leave them out of the USATX* CSVs entirely while those are 
under peer review. When these systems go live, move the already-extended 
routes over from USANSF. There's already precedent for some full routes with 
substantial non-freeway portions included in USANSF, most notably TX183 & 
TX191.
What do y'all think?



Note to self: deprecated labels as needed? (I see a few, but be sure.)
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
You can peer review these routes now; I posted a link to drafts of the full routes in the OP.

**Comment by jteresco** [comment]
Yes, let's go with 2 so those can be updated quickly and avoid that mess as we move to include the rest of the new system.

**Comment by yakra** [comment]
I was leaning toward #2 myself. Let's do it.
I'll allow time for some comments before doing a proper pull request.

Draft files:
https://github.com/yakra/HighwayData/tree/TX-temp/hwy_data/TX/TEMP

**Comment by yakra** [comment]
Just made a commit:
tx.lp012: added +I-30 AltLabel to I-30(38)

Will see if I need to add AltLabels to other files.

**Comment by yakra** [comment]
Pull #144 has been merged. Closing this issue and deleting my TX-temp branch.
