### ISSUE TITLE
NE: NE 28B

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#195]
Any reason not to add NE 28B, the part of the freeway between Omaha and Fremont that doesn't carry the US 6 or US 275 designation, to usane?

**Comment by the-spui-ninja** [comment]
Should that be a whole new system? I mean, all those links and spurs do have different shields than the rest of the state routes.

I think that they should all go in, but that's just my opinion.

Maybe make the file named like NE 28B Link (Omaha) to follow naming convention (as that's what all those links and spurs look like in OpenStreetMap (I know because I edited almost all of them))?

These are all just suggestions, by the way.

**Comment by the-spui-ninja** [comment]
Other links/spurs that should go in for sure: 
NE 7E Link (Hemingford)
NE 62A Link (Morrill County)
NE 55X Link (Lincoln)
NE 28H Link (Omaha)
NE 80E Link (Beaver Crossing)
NE 56G Link (North Platte)
NE 17J Link (Sidney)
NE 4A Spur (Harrisburg) (I threw this one it because it services a county seat)

**Comment by yakra** [comment]
This is not NE 28B, as in a full-on Nebraska state highway, but Link 28B. (L28B per the existing CHM/TM labeling conventions, or L-28B as NDOR would call it in their route logs.)

The Links and Spurs do have different shields from the state routes, and I agree that they should be a separate system.
Here's the kicker -- I actually started developing it. All the links are done, and 55/93 counties' worth of spurs. I've forgotten about it for a month or so, but it shouldn't take too much more work to finish off.

And yes, they should all go in. Except for the unsigned ones. Which would actually leave L28H out. :(

Naming: while the NDOR Log Book does associate a city or placename with each link/spur, they all have unique number/letter combinations, thus making a City & Abbrev unnecessary for our purposes.

**Comment by the-spui-ninja** [comment]
So would they go in as NE NE L28B? (Out of curiosity, you understand)

I just thought that 28H would fill a natural "gap" in the route system. I mean, it so short that signing it would be almost pointless.

**Comment by yakra** [comment]
I've been thinking of, in contrast to Texas and its Loops & Spurs, combining the Links & Spurs together into one system. Been leaning *(slightly)* toward USANES for the system code...

-----

They'd most likely go in as NE L28B, etc. Region = NE; Route = L28B (rather than NEL28B); Root = ne.l28b. This would follow the naming/labeling convention established first with the US routes and then Nebraska State Highways.

**Comment by the-spui-ninja** [comment]
Yeah, there aren't as many of these as there are loops and spurs in Texas.

**Comment by jteresco** [comment]
It makes sense to me to include them as a single separate system.

**Comment by yakra** [comment]
I've drafted files for all the Links and Spurs. I'll give them a look over, then zip`em up & send them to Jim in the coming days. But first, a couple tweaks to existing routes I found in the process.

**Comment by yakra** [comment]
Finally submitted the Nebraska State Links and Spurs to Jim via email.
Once they're in the HB, please open a new issue for anything that needs attention.
I'll also start an AARoads thread.
