### ISSUE TITLE
NM: Las Cruces

### ISSUE THREAD

**Issue by ajfarina** [TravelMapping/HighwayData#282]
A few points need to be relabeled in the Las Cruces area with the removal of I-10BL that already occurred.
NM28: I-10BL --> NM188
NM101: I-10BL --> NM188
NM478: ValDr --> NM188

Cheers.

**Comment by ovoss** [comment]
Thanx for the catch -- and the reminder that I need to add NM 188 to my own 
list file, since it includes part of the decommissioned I-10BL that I had 
previously clinched.

I'll make the changes in the next few days -- Oscar

----- Original Message ----- 
From: ajfarina
To: TravelMapping/HighwayData
Sent: Saturday, December 26, 2015 11:01 AM
Subject: [HighwayData] NM: Las Cruces (#282)


A few points need to be relabeled in the Las Cruces area with the removal of 
I-10BL that already occurred
NM28: I-10BL --> NM188
NM101: I-10BL --> NM188
NM478: ValDr --> NM188
Cheers
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages (new address):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
And why the devil was NM188 not made part of NM185? </FictionalHwys>
