### ISSUE TITLE
KY: US 60/US 231 rerouting in Owensboro

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#294]
Reported by user okroads by email:

I also wanted to bring to your attention that when I was plotting the points for U.S. 60 & U.S. 231 in the Owensboro, KY area that the points are still on the old routing on the east side of Owensboro instead of the new alignment, starting at KY 54 and going northeast to near the point marked "WriLanRd".

**Comment by ovoss** [comment]
See also http://clinched.s2.bizhat.com/viewtopic.php?t=2392&mforum=clinched, 
which discusses this reroute, and also:

-- another US 60 reroute (also affecting US 62) near Paducah; and

-- some KY state routes (including two that might be active in our data) 
affected by the Owensboro reroute, taking over part of the old US 60 
alignment.

----- Original Message ----- 
From: Jim Teresco
To: TravelMapping/HighwayData
Sent: Thursday, December 31, 2015 10:38 PM
Subject: [HighwayData] KY: US 60/US 231 rerouting in Owensboro (#294)


Reported by user okroads by email:
I also wanted to bring to your attention that when I was plotting the points 
for U.S. 60 & U.S. 231 in the Owensboro, KY area that the points are still 
on the old routing on the east side of Owensboro instead of the new 
alignment, starting at KY 54 and going northeast to near the point marked 
"WriLanRd".
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages (new address):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
#296 addresses Owensboro.
Paducah still needs attention. (Maybe a new issue for that?)

**Comment by yakra** [comment]
Paducah addressed in #320
