### ISSUE TITLE
Europe Select Named Motorways (eursf)

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/HighwayData#321]
The eursf system contains roads of several European countries. If I got it right, they have motorway standard but are not signed as motorways (e.g. no official motorway number) or "which are not part of the highest road category or motorway category of the respective country". http://tm.teresco.org/devel/hb.php?sys=eursf

For instance, the Spanish and French routes are regional motorways but not A road category but not the entire network with this numbering, e.g. not all French D roads.

I think the German "Yellow Autobahns" do have the same category, don't they?

They are Federal B roads which have motorway standard, are tolled for trucks and are usually without general speed limit for cars (like Autobahns). There's a map showing all tolled B roads: http://www.bmvi.de/SharedDocs/DE/Anlage/VerkehrUndMobilitaet/Strasse/karte-mautpflichtige-bundesstrassen-ab-2015-07-01.pdf?__blob=publicationFile (There are some 2-laned tolled B roads which do not have motorway standard though).

@si404 , you are responsible for Germany but do you think it's possible that I make a wpt file for the German "Yellow Autobahns" over the next months?

**Comment by si404** [comment]
It's a little bit more complex than that.

My criteria for inclusion was one of the following:
- was on CHM but doesn't fit into enlarged tier 1 category based on shield type in Spain and Italy
- is a motorway in a country without a separate motorway system - eg Denmark
- is an expressway in a country with a motorway system that isn't on the national roads level - eg France (though using the 'select' nature of the system just to add ones I thought were useful to add)
- is part of the motorway system of a country, but has a name, rather than a number - eg Switzerland

Gelb Autobahn don't really fit into it.
- They aren't leftovers, so don't fit the Spainish/Italian criterum
- There is a separate motorway system, so don't fit the Danish criterium
- They are at the national roads level, so don't fit the French criterium

B road files, are a different kettle of fish, and I say why not give a few routes a go, and I'll have a look to see if you are doing them right before you spend lots of time making lots of routes.

**Comment by michihdeu** [comment]
I think it's important to have rules but they are not set in stone!

I'll make some files but I'm not sure how to provide them.

If I got it right I cannot upload files without installing something on my computer "you have set up your GitHub environment on your own computer" https://github.com/TravelMapping/HighwayData/wiki/Fork-%26-Pull-Instructions-for-Highway-Data-Updating.

I could send you (or Jim?) an email but I would need your email address, Si.

**Comment by si404** [comment]
You can upload files in other ways - see github help for details. Certainly a few files can easily be done in-browser (only really bulk that is the issue).

my email is sh1604 <snail> gmail.com (using snail because it is the cool dutch term for the @ symbol)

**Comment by si404** [comment]
Replying to email here:

1. Again, German Yellow Autobahn do **not** meet the criteria for eursf as they are not full motorways (unlike the Belgium Ring Autosnelwegen/Autoroutes, and the Basque N-I that I now ought to add) and are part of a (potential) tier-4 system.

2. I suggested B road files, not Autobahn-like bits of B roads. I don't give two hoots whether or not these bits are tolled for trucks! That you put 'tolled for trucks' and 'divided' as the criteria for entry, and have roads that are at-grade makes me confused - I thought you were trying to put routes into eursf and excluding a lot of the B road system as they aren't "tier 2 category"? Does the at-grade road even have the 'happy car' sign?

3. The files are the right idea, but there's a few things (besides not listening to me that Yellow Autobahn won't get into eursf).
 * Labels - those prefixes are weird! Can we have one prefix for district roads? Tim's proposal on CHM for using different prefixes for county roads (eg name of the county abbreviated), rather than a generic one was a unanimously panned proposal. Or are they actually signed as WUE, SW, AB, etc?If the latter, then fine go with it. Ditto Lander/State roads (aren't they mapped on OSM, etc as 'Lx'?)
 * Shaping - there ought to be a tolerance line on the .wpt creator program - if the road leaves it, hidden points would be needed.
 * GSJs - always include a grade-separated junction, even if there's an at-grade one with a more major road nearby (not an issue in the files you sent, but from your review comments it seems you haven't learnt this rule).

Give me the B8, B19, B27, B286, B303 and B469 showing their whole routes, not just the dual carriageway truck vignette bits, and you should be about there. The big problem with your files is not listening to me when I said that they will not go in eursf. We're looking at deub here.
