### ISSUE TITLE
QC/NB: TCH realignments, and new A-85 segments

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#35]
http://clinched.s2.bizhat.com/viewtopic.php?t=2307

Looking ahead to submitting a pull request for my newsworthy New Brunswick updates.
Oscar, do you have the TCH edits ready to go for the Quebec side of the border?

**Comment by ovoss** [comment]
Eric:

I don't have the QC side ready yet. I can't find some rough partial drafts 
I'd done, so I'd need to start from scratch. I'm also awaiting more clarity 
on whether traffic is going to be moved next week from the old TCH (QC 185) 
to half of the new A-85 roadway between Degelis and Notre-Dame-du-Lac. 
That'd let me do one new A-85 segment between the NB border and 
St-Louis-du-Ha! Ha!, and related TCH changes, rather than do two segments 
only to go back in a few months to fill the gap.

Oscar

----- Original Message ----- 
From: Eric Bryant
To: TravelMapping/HighwayData
Sent: Thursday, August 13, 2015 2:58 PM
Subject: [HighwayData] QC/NB: TCH realignments, and new A-85 segments (#35)


http://clinched.s2.bizhat.com/viewtopic.php?t=2307
Looking ahead to submitting a pull request for my newsworthy New Brunswick 
updates.
Oscar, do you have the TCH edits ready to go for the Quebec side of the 
border?
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages:  http://home.comcast.net/~oscar.voss/
Hawaii Highways:  http://www.hawaiihighways.com/

**Comment by yakra** [comment]
Oscar will include nb.nb002.wpt & nb.tchmai.wpt in his pull request.

**Comment by jteresco** [comment]
At least some of this is now in the DB.

**Comment by yakra** [comment]
Oscar, is there anything left to do here? Or is this issue safe to close?

**Comment by ovoss** [comment]
Nothing left to do, for a few years. Close.

----- Original Message -----
