### ISSUE TITLE
Systems in development missing _con.csv files

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#4]
The cannf and cansph in-development systems are temporarily out of systems.csv because they lack _con.csv files, which are now required for a system to be processed into the DB.  This should be fixed once we move forward on making fixes to existing systems.

**Comment by jteresco** [comment]
Also usaky4, usasc, and usala1 are missing _con.csv files and are temporarily leaving systems.csv.

**Comment by jteresco** [comment]
One more: usafl.

**Comment by jteresco** [comment]
usaca too.

**Comment by si404** [comment]
All of these are stalled in-dev systems. cannf and cansph are just holding grounds.

**Comment by ovoss** [comment]
usaca has missing fields in its csv files, but that can be addressed along with other csv changes (including updates for new and decommissioned routes) once development restarts on that system.

**Comment by yakra** [comment]
So if I make a cansph_con.csv, it can be uncommented from systems.csv, and thus included in the HB. (Right?) Still InDev, of course.

I may just take that on when I remove the CANAB routes from cansph.csv. Which may happen Real Soon Now.

**Comment by jteresco** [comment]
Yes, I'm happy to include any system in development at pretty much any partial stage as long as it has a valid .csv and _con.csv file.  In particular, I'd like to see usafl, usaca, and usasc get to the point that the routes in development so far can be included.

**Comment by yakra** [comment]
usasc_con.csv exists now, but usasc is still commented out of systems.csv.

The following systems are still missing _con.csv files:
* cannf
* usafl
* usaky4
* usala1

**Comment by jteresco** [comment]
Are the current usafl routes plotted so far in good enough shape that they could be added as a devel system if a _con.csv file could be created?

**Comment by yakra** [comment]
usasc, usafl, and usala1 are visible in the HB now.

**usaky4** is hidden due to nonstandard formatting in usaky4.csv. I interpret a blank final column as "unknown" rather than "unsigned". Maybe this info could be moved into a GitHub issue, or topic on the TM forum.

That leaves **cannf**. Personally I see it as a very low priority and am content to let it gather dust indefinitely. But OTOH it might be nice to make cannf_con.csv, get it into the HB, and close this issue.

**Comment by yakra** [comment]
#368 will take care of **cannf**.
This takes care of everything enumerated in this thread. Some of Si's newer (or, planned?) systems don't have CSVs at all and are commented out of systems.csv. But I'm sure he's on top of that, so not to worry.

While **usaky4**_con.csv does exist, usaky4.csv still needs to lose that last column in order to uncomment this system. I've started to look into the signing status of the 24 routes not marked as "signed" in order to sort this out.

Once usaky4 gets added as in-dev, IMO this issue will be ready to close.
