### ISSUE TITLE
MO/WI/IL/SD Updates

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#60]
Jeff M. sent me all of the updates he submitted to CHM since that project went dormant.  I can work through them and get them in, but it won't happen right away.  Any volunteers?  Basically you'd need to look through the updated files, make sure other updates weren't made to them since he updated his copies, put them in the right places in our new hierarchy, add updates.csv entries as needed, and submit a pull request.  Thanks.

**Comment by ovoss** [comment]
Let me take a shot at this.  I'm especially curious whether the package 
includes the new I-41, and associated changes in WI.

----- Original Message ----- 
From: Jim Teresco
To: TravelMapping/HighwayData
Sent: Thursday, August 27, 2015 10:52 PM
Subject: [HighwayData] MO/WI/IL/SD Updates (#60)


Jeff M. sent me all of the updates he submitted to CHM since that project 
went dormant. I can work through them and get them in, but it won't happen 
right away. Any volunteers? Basically you'd need to look through the updated 
files, make sure other updates weren't made to them since he updated his 
copies, put them in the right places in our new hierarchy, add updates.csv 
entries as needed, and submit a pull request. Thanks.
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages:  http://home.comcast.net/~oscar.voss/
(being relocated to http://www.alaskaroads.com/home.html)

**Comment by jteresco** [comment]
Great, thanks.  Jeff said he held off on I-41, as it made more sense to get some US 41 updates in first.  Watch your email for a zip of his files.

**Comment by jteresco** [comment]
These are now in, so I'm closing the issue.  Please open new issues if problems are noticed with the updated data.
