### ISSUE TITLE
NY: I-390

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#65]
http://clinched.s2.bizhat.com/viewtopic.php?t=2301&mforum=clinched

So when this is fixed, am I seeing the situation correctly in that 16 remains where it is at the NY 15A interchange, a new 16B gets added centered over NY 15, and 16A moves to be centered over Kendrick Rd?

**Comment by vdeane** [comment]
That could work, though with the current project to split the NB interchange with NY 15 and NY 15A (as it is SB), that could affect things.

**Comment by yakra** [comment]
There's no real way to win on point labeling here.
*16A moves to be centered over Kendrick Rd; that much is clear.
*16B is signed for the NY15A exit.

Reminds me of NH I-95 Exit 3. Driving south, you encounter first 3A and then 3B. But alphanumerically, it's out of order: 5, 4, 3A, 3B, 2...
(Thus I understand labeling NY15A as Exit 16 instead of 16B when first drafting the Interstates: it Looks Nicer.)
Whatever happens, exit numbers will be out of order:
*16, 16B, 16A as Jim posits in the OP.
*16B, 16, 16A as I'd prefer it. Having 16B point to the road that exit number isn't actually signed for doesn't sit well with me, and IMO changing the 16 label to map to a slightly different location is the lesser evil.
*O HAY! How about 16B+16, 16C, 16A? This avoids changing how .list files are parsed.
*Or even just 16, 16C, 16A, avoiding the AltLabel and leaving 16B open for future use. Because...

As @vdeane points out, construction is still underway. Switch the HB to Mapnik view to see the U/C ramps. I see potential for exit renumbering and/or alphabet soup here: What's now simply Exit 16 NB could be Exit 16A/B/C as a flurry of ramps depart the mainline. Or it could stay as one Exit 16 ramp which departs the mainline and then splits in three. Or, one ramp could leave-and-then-split, and be signed "Exits 16A-B-C", as I've seen done in MA (and maybe CT).

I almost wanna twiddle my thumbs on this for a while, and see how the completion of the project affects things.

And then, when NY finally switches to milepost-based exit numbering, we get to go thru the whole thing again. :P

**Comment by vdeane** [comment]
FYI: NB, I-390 has 16B for NY 15A north and 16A is for NY 15A south and NY 15.

**Comment by yakra** [comment]
A bit of thinking out loud here...
NYSDOT's exit (re?)numbering choices were stupid. But it's what we've got to work with... :(
But anyway.
The good news is, neither 16 nor 16A are PointsInUse, so we're free to do what we want with these labels. Kendrick Rd doesn't necessarily have to be 16A, and "changing the 16 label to map to a slightly different location" is not a problem.

All the Exit 16Bs go to NY15A and NY15A only, so this should be labeled 16B. That much is clear at least.
IMO, both NY15 and Kendrick Rd should get points. Each one has 3/4 of a full interchange. (Heck, a full interchange for NY15, if you also count the SB "misbehaving parclo" ramps as serving it.)
Thing is, there's just one exit number (16A) available for the two of`em, as things are signed. That's what you get when there are more onramps than offramps. So, fudging in a new point label will have to come into play somewhere somehow.
Keeping the 16A label all the way west is less attractive to me with one flavor of 16A serving NY15A...

The more I think about it, the more I like:
**16B:** NY15A
**16A:** NY15
**16:** Keendrick Rd
It Looks The Nicest, keeping things in a nice alphanumeric order -- at least amid the Exit 16Xs themselves. Still not so hot when you add in 15 & 17 on either side to get 15, 16B, 16A, 16, 17, but hey. Whatchagonnado... <glares at NYSDOT>

How about it? Any objections?
