### ISSUE TITLE
UT: usaut updates

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#662]
Crossposting this from the forum so it doesn't get buried:
UT 176: New route (Vineyard Connector)
UT 48: Truncated to UT 154
UT 209: absorbed old UT 48
UT 73: split into two segments
UT 145: extended west
UT 197: decommissioned
UT 154: new numbered exits
UT 151: extended to US 89 (maybe)

http://tm.teresco.org/forum/index.php?topic=173.0 for full details

**Comment by the-spui-ninja** [comment]
New issues:
UT 140: truncated from UT 68 to 800 W in Bluffdale.
UT 131: another new route? This is in the same area as UT 140.

UDOT Reference guide: https://maps.udot.utah.gov/highway/f?p=184:4

**Comment by the-spui-ninja** [comment]
Also:
UT 92: extends west from I-15 to Ashton Blvd.

**Comment by the-spui-ninja** [comment]
Most of this dealt with by #1260, except potentially UT 92 and UT 131. The reference site changed links: https://maps.udot.utah.gov/uplan_data/documents/HRO/

**Comment by mapcat** [comment]
@NickCPDX: looks like 92 & 131 have not been edited yet

**Comment by NickCPDX** [comment]
Fixed 92. Not adding 131 yet, I see no indication that it's signed.

**Comment by Duke87ofST** [comment]
Addressed in the pull linked below are:
- Updates to UT 85, 107, 193, 225, and 252
- UT 146 deleted
- UT 129 and 135 added

These items were all brought up on the forum last fall and had been languishing unaddressed. As Utah is nominally Nick's region I will refrain from making any more updates to it... I stepped in on these only because the ball appeared to have been dropped and someone was complaining that the updates hadn't been made.

https://github.com/TravelMapping/HighwayData/pull/2075

**Comment by michihdeu** [comment]
Can anyone please close this. Thx.

**Comment by the-spui-ninja** [comment]
Okay
