### ISSUE TITLE
NY 12 in Watertown

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#7]
NY 12 is signed concurrent with US 11 in Watertown, but no concurrency exists in its routing in our data.

**Comment by jteresco** [comment]
Decided to look at this a bit tonight, and it seems there's more to figure out and fix in Watertown.
- NY12E's NY12_S point doesn't have a corresponding point on NY12.
- NY12F doesn't connect to NY 12 at all.
- It is unclear to me how NY 12 and US 11 get through the center of Watertown.

**Comment by yakra** [comment]
THE DEVIL.
The way OSM shows things indicates couplets. Not one-way couplets mind you, but two-way couplets. Yeah. What's shown is borne out in StreetView -- mostly.

NY12: NB, Mill & Main. SB, Massey, Arsenal & Public Square. What I'd do here is just have it cut from one corner of the box to the other, NY3_W to US11_N, favoring neither the NB nor SB alignments. Delete US11_A (not in use), and make NY283 (in use on CHM) an AltLabel for NY3_W.

US11 is a little more wibbly-wobbly.
NB, from Paddock/Winslow, signage has it continuing straight on Washington, taking a right onto Public Square, then turning north onto Mill St. Signage at the NY283 junction has it continuing straight, and that's the last signage we have until it rejoins the SB routing at Leray St. Interestingly, at Mill & Main, there's signage for NY12 turning left onto West Main, but no signage for US11.
The SB routing is clear as day; Leray, Massey, Holcomb, Paddock. The waters are muddied a bit by the fact that every major junction on Massey between Main & Arsenal has Massey clearly signed as US11 North. From every direction. Even though following US11 NB from Washington & Paddock/Winslow will take you elsewhere. I saw no US11 NB signage on Paddock or Holcomb.
This reminds me of how US1 NB in Portland was signed on both Valley St and St John St until it was relocated onto I-295 in 2007.
It also reminds me of MA US202 in Holyoke: It's signed via Beech St NB, but signage, junctions, yadda yadda... I forget my exact rationale 8ish years later but I chose the SB alignment to represent the route for CHM purposes.
The NYS Traffic Data Viewer ( http://gis3.dot.ny.gov/html5viewer/?viewer=tdv ) has a US11 marker pretty close to Mill St at the right zoom level. Zoom in twice more and the text "US Highway 11" label bends down to parallel Mill from the Mill/Leray junction. FWIW.
What I'm leaning toward right now is, rather than pulling a Holyoke, considering US11 to be a Mill/Leray/etc./etc. couplet. As far as actual point placement... yecch.

NY12E: Its endpoint is needed on NY12 any way you slice it.

NY12F: It connects to NY12 SB. Which is also signed for NY12 NB at that location. (As from NY3 as well. Because why send people all the way around the other 3 sides of the square just to continue north? More sensible wayfinding. Think of it as a case of a missing [TO] if you will.) This endpoint is fine.

NY3: The argument could be made to add waypoints at Massey and Mill. But what to label them? Grumble.

NY283: The endpoint is fine, though I'd probably take the opportunity to tweak the coords a bit. And maybe relabel it US11/12.

**Comment by yakra** [comment]
View my proposed changes here:
https://github.com/TravelMapping/HighwayData/compare/master...yakra:Watertown-NY

**Comment by yakra** [comment]
I'll allow a few days for comment before making a formal pull request from this branch.

**Comment by vdeane** [comment]
That seems to be right.  There's a US 11 reference marker on Mill at the Watertown city line.  The traffic stationing also uses it as the main alignment (they always use the primary inventoried direction, generally NB/EB, but there's at least one exception (I-890)) as do the station numbers.

**Comment by yakra** [comment]
Thanks for the confirmation. Shall I make a pull request, then?

**Comment by vdeane** [comment]
No objections from me.

**Comment by jteresco** [comment]
OK by me too.
