### ISSUE TITLE
FL: State Highway file names

### ISSUE THREAD

**Issue by rickmastfan67** [TravelMapping/HighwayData#89]
I'm just curious, but should we add in an extra '0' to the route numbers in the files?

The reason I'm asking is because Florida does have 'one' posted 4 digit highway, FL-9336. [1]  I know other states (like Kentucky) have the extra '0' in the files.

If we're going to add the extra '0', @jteresco, do you know of a quick way to add it into the file names here on GitHub?  The reason I ask is because I think there are too many files to do it manually.  Also, how would we want to deal with A1A's file names?  fl.0a1a?  Doesn't look right, but maybe for that route, we could skip adding the '0'?

[1] - https://en.wikipedia.org/wiki/Florida_State_Road_9336

**Comment by jteresco** [comment]
I don't know about GitHub, but I can write a script to rename them.  I think we should use leading 0's for the "normal routes" to make them 3 digits, and call A1A and 9336 special cases.

I noticed a lot of Europe routes aren't using the extra 0's.  I don't care much and probably wouldn't have bothered if I was the decision maker when CHM started, but I do think we should be consistent.

**Comment by rickmastfan67** [comment]
The routes currently are already setup for the '3-digits' in FL.  They have been from the start.  I just didn't know if we wanted to change them all to 4-digits via an extra leading 0 because of the existence of FL-9336.

**Comment by jteresco** [comment]
I definitely wouldn't be in favor of going 4 digits, but Tim did that for Kentucky.  However, there are many, many 4-digit routes in Kentucky.

**Comment by yakra** [comment]
In the case of Texas USANSF routes, there's just one 4-digit route, tx.lp1604fwy. All the other routes use 3-digit filenames.
I think, if there's just one 4-digit route, it's fine to do it this way.
Especially if it's a matter of going to all the bother of writing a script to convert, and the (small) risk of breaking (inactive) things...

**Comment by ovoss** [comment]
Hawaii has eight four-digit routes in the HB. But the filenames for its 
three-digit routes have no leading zeroes, and the ones for the two-digit 
routes each have only one leading zero.

----- Original Message -----

**Comment by si404** [comment]
Here's the Europe situation:

Due the to the 3-digit routes E001-E019, E Road file names don't have leading zeros (even when, like the E01 in Ireland, it's signed as such, because Tim wanted consistency over accuracy and made two-digit routes under 10 one-digit routes as the 'majority' are signed without the leading zeros the routes are defined as having) because Tim didn't want the issue (though there wouldn't be any) of clashes.

British A roads - while there's a butt ton of four digit routes, Tim didn't bat an eyelid but I just simply used 3-digit file names for non-four digit routes. All other routes are 3-digits with leading zeros and no 4-digit routes in the system.

The Swiss A1a, the French A5a, A6b, etc are che.a001a, fra.a005a, fra006b, etc, however I suggest fl.fla1a would be simpler and consistent - it's not like a semi-bannered route (eg MT200S, or US1A, or whatever) that the Autoroute are.

**Comment by jteresco** [comment]
This all makes sense as is to me.  I certainly at least see no reason to go back and change anything in systems that are already developed using criteria that were good enough for CHM.

**Comment by jteresco** [comment]
Seems we're leaving this as is.  Closing.
